"""Assemble le dossier unique ORI-C : un socle commun et trois branches.

Aucun chemin absolu. Les répertoires sources et la destination sont passés en
argument. Le script copie, il ne déplace jamais.

    python construire_dossier.py --sources <rep> --destination <rep>
    python construire_dossier.py --sources <rep> --verifier-reconstruction

La seconde forme reconstruit le dossier dans un répertoire temporaire à partir
des mêmes sources, puis compare le manifeste obtenu à celui du dossier courant.
Elle échoue si la reconstruction n'est pas identique.

Arborescence attendue sous `--sources` :

    dossier_consolide/    extraction de tests.zip du dossier consolidé
    tests_memoire/        paquet ORI-C_tests_memoire_historique
    validation_ncorps/    paquet ORI-C_Systeme_solaire_validation_scientifique_maximale
    articles/             les PDF et DOCX des trois branches

Les fichiers rédigés pour le dossier lui-même — README, ARCHITECTURE,
ETAT_DES_PREUVES, CODEBOOK, READMEs de branches, erratum, ce script et le
vérificateur — n'appartiennent à aucune source. Ils sont préservés lors d'une
reconstruction en place.
"""

from __future__ import annotations

import argparse
import hashlib
import shutil
import sys
import tempfile
from pathlib import Path

EXCLUS_REPERTOIRES = {
    "__pycache__", ".pytest_cache", ".git", "node_modules", ".claude",
    ".mplconfig",
}
EXCLUS_SUFFIXES = {".pyc", ".pyo"}
EXCLUS_NOMS = {
    "data.zip", "tests.zip", "MANIFEST.sha256", "MANIFEST_SHA256.txt",
    # Le manifeste JSON est ecrit par build_manifest.py. L inscrire ici le
    # rendait perpetuellement obsolete : chaque regeneration modifiait un
    # fichier deja empreinte, et le verificateur le signalait absent.
    "MANIFEST.sha256.json",
    # Doublon sans extension du fichier .dot, retiré du paquet.
    "carte_relationnelle_oric_47",
}

FICHIERS_REDIGES = (
    "README.md",
    "audit/validation_archive.json",
    "verifier_fusion.py",
    "plateforme/campagne_maximale_reelle/BILAN_CANONIQUE.md",
    "plateforme/campagne_maximale_reelle/resultats_consolides/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_consolides/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_consolides/results.json",
    "DATA_AVAILABILITY.md",
    "VERSION",
    "LICENSE",
    "LICENSE_PENDING.md",
    "documentation/ALIASES_DOCUMENTAIRES.md",
    "scripts/construire_archive_canonique.py",
    "SCIENTIFIC_SCOPE.md",
    "build_manifest.py",
    ".gitignore",
    ".github/workflows/clean-extraction.yml",
    "plateforme/source_corrigee/requirements-lock.txt",
    "plateforme/source_corrigee/tests/test_gistemp_scope.py",
    "ARCHITECTURE.md",
    "ETAT_DES_PREUVES.md",
    "ETAT_DES_TESTS.md",
    "AUTORITE_DES_DOCUMENTS.md",
    "construire_dossier.py",
    "verifier_dossier.py",
    "etat_des_tests.py",
    "00_socle/README.md",
    "00_socle/CODEBOOK.md",
    "00_socle/PROTOCOLE_DONNEES.md",
    "00_socle/valider_donnees.py",
    "00_socle/schemas_donnees/exemple/etats.csv",
    "00_socle/schemas_donnees/exemple/evenements.csv",
    "00_socle/schemas_donnees/exemple/relations.csv",
    "00_socle/carte_relationnelle/REGENERATION_REQUISE.md",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/i_criteres_discriminants.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/j_mecanismes_wp_c7.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/k_familles_wp_c4.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/l_familles_memoire_wp_c3.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/m_prospectif_wp_c2.py",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/criteres_discriminants.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mecanismes_c7.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/familles_c4.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/familles_memoire_c3.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif_c2.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/i_criteres_discriminants.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/i_criteres_discriminants.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/j_mecanismes_wp_c7.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/j_fenetres_wp_c7.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/k_familles_wp_c4.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/k_familles_wp_c4.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/l_familles_memoire_wp_c3.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/l_familles_memoire_wp_c3.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/RAPPORT_WP_C3.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/RAPPORT_WP_C4.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/RAPPORT_WP_C6.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/RAPPORT_WP_C7.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif_c2/PROTOCOLE_C2.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif_c2/prospectif_c2.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif_c2/RAPPORT_WP_C2.md",
    "ENVIRONNEMENT.md",
    "enregistrer_environnement.py",
    "plan_directeur/GRILLE_ETAPE_2.md",
    "plan_directeur/AUDIT_TRANSVERSAL.md",
    "plateforme/campagne_maximale_reelle/EXCLUSIONS.md",
    "00_socle/carte_relationnelle/data/cas_exoplanetes.csv",
    "00_socle/carte_relationnelle/resultats/audit_carte_relationnelle_oric_47.txt",
    "00_socle/carte_relationnelle/resultats/carte_relationnelle_oric_47.dot",
    "00_socle/carte_relationnelle/resultats/carte_relationnelle_oric_47.pdf",
    "00_socle/carte_relationnelle/resultats/carte_relationnelle_oric_47.png",
    "00_socle/carte_relationnelle/resultats/carte_relationnelle_oric_47.svg",
    "00_socle/carte_relationnelle/resultats/carte_relationnelle_oric_47_complete.pdf",
    "00_socle/carte_relationnelle/resultats/matrice_relations_oric_47.csv",
    "00_socle/carte_relationnelle/resultats/registre_relations_oric_47.pdf",
    "00_socle/carte_relationnelle/scripts/generer_carte_relationnelle_oric.py",
    "00_socle/note_integration/Note_integration_ORI-C.docx",
    "00_socle/schema_synthetique/ORI-C_carte_relationnelle_TR001_TR040_stabilisee.pdf",
    "00_socle/schema_synthetique/README.md",
    "00_socle/test_interventionnel/resultats/metriques_test_interventionnel_ori_c.json",
    "00_socle/test_interventionnel/resultats/rapport_test_interventionnel_ori_c.txt",
    "00_socle/test_interventionnel/resultats/resultats_test_interventionnel_ori_c.csv",
    "00_socle/test_interventionnel/resultats/test_interventionnel_ori_c.pdf",
    "00_socle/test_interventionnel/resultats/test_interventionnel_ori_c.png",
    "00_socle/test_interventionnel/resultats_robustesse/rapport_robustesse.txt",
    "00_socle/test_interventionnel/resultats_robustesse/robustesse_test_interventionnel.json",
    "00_socle/test_interventionnel/resultats_robustesse/robustesse_test_interventionnel.pdf",
    "00_socle/test_interventionnel/resultats_robustesse/robustesse_test_interventionnel.png",
    "00_socle/test_interventionnel/scripts/modele_ori_c.py",
    "00_socle/test_interventionnel/scripts/robustesse_test_interventionnel.py",
    "00_socle/test_interventionnel/scripts/test_interventionnel_ori_c.py",
    "00_socle/tests/test_modele_interventionnel.py",
    "01_branche_matiere/article/Chronologie_des_architectures_de_la_matiere_ORI-C.docx",
    "01_branche_matiere/article/Chronologie_des_architectures_de_la_matiere_ORI-C.pdf",
    "01_branche_matiere/article/variantes/ORI-C_document_unique_sans_fusion_des_contenus.pdf",
    "01_branche_matiere/base_transitions/enrichir_dimensions.py",
    "01_branche_matiere/base_transitions/information_dimensions.json",
    "01_branche_matiere/base_transitions/mesurer_dimensions.py",
    "01_branche_matiere/base_transitions/qualite_dimensions.json",
    "01_branche_matiere/base_transitions/sources_dimensions.csv",
    "02_branche_systeme_solaire/application_climat/Le_climat_comme_architecture_historique_ORI-C.docx",
    "02_branche_systeme_solaire/article/Architecture_historique_du_Systeme_solaire_ORI-C.pdf",
    "02_branche_systeme_solaire/couche_astronomique/LISEZ_MOI.md",
    "02_branche_systeme_solaire/couche_astronomique/MANIFESTE.json",
    "02_branche_systeme_solaire/couche_astronomique/REPRODUCTION.md",
    "02_branche_systeme_solaire/couche_astronomique/SHA256SUMS.txt",
    "02_branche_systeme_solaire/couche_astronomique/STATUT_SCIENTIFIQUE.md",
    "02_branche_systeme_solaire/couche_astronomique/VALIDATION_FINALE.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/.gitattributes",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/.github/workflows/ci.yml",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/.gitignore",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/CITATION.cff",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/LICENSE",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/Makefile",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/README.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/VALIDATION.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/configs/real_science_max.yaml",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/configs/rebound_quickcheck.yaml",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/configs/rebound_science_2myr.yaml",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/configs/smoke_surrogate.yaml",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/HORIZONS_PROVENANCE.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/horizons_j2000_de441.csv",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/horizons_j2000_de441_raw.json",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/planetary_j2000.csv",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/horizons/PROVENANCE.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/horizons/earth_elements_j2000_to_minus6kyr.csv",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/horizons/earth_elements_j2000_to_minus6kyr_raw.json",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/La2010a_ecc3.dat",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/La2010a_ecc3L.dat",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/La2010b_ecc3.dat",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/La2010c_ecc3.dat",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/La2010d_ecc3.dat",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/PROVENANCE.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/data/reference/la2010/README.TXT",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/docs/OUTPUT_SCHEMA.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/docs/REAL_SCIENCE_RESULTS.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/docs/TEST_PLAN.md",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/docs/source/Architecture_historique_du_Systeme_solaire_ORI-C_revue.docx",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/pyproject.toml",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/requirements.lock.txt",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/requirements.science.lock.txt",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/analyze_real_science_suite.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/build_max_validation_package.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/fetch_horizons_earth_validation.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/fetch_horizons_j2000.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/run_real_science_suite.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/run_rebound_quickcheck.ps1",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/run_rebound_quickcheck.sh",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/run_smoke.ps1",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/scripts/run_smoke.sh",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/__init__.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/__main__.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/archives.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/backends/__init__.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/backends/rebound_backend.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/backends/surrogate.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/catalog.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/cli.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/climate.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/config.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/data/horizons_j2000_de441.csv",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/data/planetary_j2000.csv",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/experiment.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/insolation.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/manifest.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/real_validation.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/reporting.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/src/oric_solar_history/spectral.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_config.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_insolation.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_package_builder.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_pipeline.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_real_validation.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_rebound_backend.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_spectral.py",
    "02_branche_systeme_solaire/couche_astronomique/code/ORI-C_Systeme_solaire_tests/tests/test_surrogate.py",
    "02_branche_systeme_solaire/couche_astronomique/distribution/oric_solar_history-0.2.0-py3-none-any.whl",
    "02_branche_systeme_solaire/couche_astronomique/documents/Architecture_historique_du_Systeme_solaire_ORI-C_revue.docx",
    "02_branche_systeme_solaire/couche_astronomique/documents/Architecture_historique_du_Systeme_solaire_ORI-C_revue.pdf",
    "02_branche_systeme_solaire/couche_astronomique/git/ORI-C_Systeme_solaire_tests.bundle",
    "02_branche_systeme_solaire/couche_astronomique/integration_reelle/AVERTISSEMENT.md",
    "02_branche_systeme_solaire/couche_astronomique/integration_reelle/excentricite_terre.csv",
    "02_branche_systeme_solaire/couche_astronomique/integration_reelle/integration_2Ma.log",
    "02_branche_systeme_solaire/couche_astronomique/integration_reelle/integration_reelle.json",
    "02_branche_systeme_solaire/couche_astronomique/integration_reelle/integrer_systeme_solaire.py",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/SCIENTIFIC_VALIDATION_REPORT.md",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/acceptance_tests.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/analysis_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/analysis_summary.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/counterfactual_band_metrics.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/counterfactual_effects.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/ensemble_divergence.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/ensemble_divergence_binned.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/counterfactual_effects.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/ensemble_divergence.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/horizons_reference_6kyr.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/multitaper_spectra.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/numerical_invariants.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/reference_correlation_horizon.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/figures/reference_first_2myr.png",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/horizons_reference_metrics.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/job_integrity.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/job_summaries.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/la2010_ensemble_spread.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/numerical_comparisons.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/peaks_baseline_20myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/peaks_la2010a_20myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/reference_ensemble_metrics.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/reference_metrics_by_horizon.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/roundtrip_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectral_band_comparison.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectral_stability_405k.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_baseline_20myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_baseline_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_jupiter_a_minus_0p5pct_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_jupiter_a_plus_0p5pct_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_jupiter_mass_minus_5pct_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_jupiter_mass_plus_5pct_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_la2010a_20myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_saturn_mass_minus_5pct_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/analysis/spectrum_saturn_mass_plus_5pct_2myr.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_20myr_dt10/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_20myr_dt10/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_20myr_dt10/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_20myr_dt10/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_20myr_dt10/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_20myr_dt10/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt4p8828125/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt4p8828125/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt4p8828125/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt4p8828125/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt4p8828125/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt4p8828125/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt5/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt5/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt5/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt5/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt5/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_dt5/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_elements_dt5/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_elements_dt5/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_elements_dt5/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_elements_dt5/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_elements_dt5/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_elements_dt5/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_no_gr_dt5/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_no_gr_dt5/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_no_gr_dt5/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_no_gr_dt5/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_no_gr_dt5/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/baseline_2myr_no_gr_dt5/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r00/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r00/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r00/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r00/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r00/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r00/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r01/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r01/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r01/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r01/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r01/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r01/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r02/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r02/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r02/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r02/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r02/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r02/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r03/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r03/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r03/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r03/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r03/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r03/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r04/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r04/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r04/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r04/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r04/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r04/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r05/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r05/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r05/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r05/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r05/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r05/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r06/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r06/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r06/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r06/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r06/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r06/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r07/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r07/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r07/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r07/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r07/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ensemble_10myr_r07/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/execution_results.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/full_la2010_bodies_2myr_dt5/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/full_la2010_bodies_2myr_dt5/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/full_la2010_bodies_2myr_dt5/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/full_la2010_bodies_2myr_dt5/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/full_la2010_bodies_2myr_dt5/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/full_la2010_bodies_2myr_dt5/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grfull_20kyr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grfull_20kyr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grfull_20kyr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grfull_20kyr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grfull_20kyr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grfull_20kyr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grpot_20kyr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grpot_20kyr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grpot_20kyr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grpot_20kyr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grpot_20kyr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/ias15_grpot_20kyr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_minus_0p5pct_2myr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_minus_0p5pct_2myr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_minus_0p5pct_2myr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_minus_0p5pct_2myr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_minus_0p5pct_2myr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_minus_0p5pct_2myr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_plus_0p5pct_2myr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_plus_0p5pct_2myr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_plus_0p5pct_2myr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_plus_0p5pct_2myr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_plus_0p5pct_2myr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_a_plus_0p5pct_2myr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_minus_5pct_2myr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_minus_5pct_2myr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_minus_5pct_2myr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_minus_5pct_2myr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_minus_5pct_2myr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_minus_5pct_2myr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_plus_5pct_2myr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_plus_5pct_2myr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_plus_5pct_2myr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_plus_5pct_2myr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_plus_5pct_2myr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/jupiter_mass_plus_5pct_2myr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/resolved_config.yaml",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/roundtrip_100kyr_dt10/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/roundtrip_100kyr_dt10/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/roundtrip_100kyr_dt10/roundtrip_errors.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/roundtrip_100kyr_dt5/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/roundtrip_100kyr_dt5/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/roundtrip_100kyr_dt5/roundtrip_errors.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_minus_5pct_2myr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_minus_5pct_2myr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_minus_5pct_2myr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_minus_5pct_2myr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_minus_5pct_2myr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_minus_5pct_2myr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_plus_5pct_2myr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_plus_5pct_2myr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_plus_5pct_2myr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_plus_5pct_2myr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_plus_5pct_2myr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/saturn_mass_plus_5pct_2myr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/suite_metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/whfast_grpot_20kyr/body_summary.csv",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/whfast_grpot_20kyr/diagnostics.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/whfast_grpot_20kyr/earth.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/whfast_grpot_20kyr/job_manifest.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/whfast_grpot_20kyr/metadata.json",
    "02_branche_systeme_solaire/couche_astronomique/resultats/real_science_max/whfast_grpot_20kyr/orbital_sample.csv.gz",
    "02_branche_systeme_solaire/couche_astronomique/scripts/verifier_paquet.py",
    "02_branche_systeme_solaire/couche_memoire_historique/CITATION.cff",
    "02_branche_systeme_solaire/couche_memoire_historique/METHODS.md",
    "02_branche_systeme_solaire/couche_memoire_historique/RAPPORT_CORRIGE.md",
    "02_branche_systeme_solaire/couche_memoire_historique/README.md",
    "02_branche_systeme_solaire/couche_memoire_historique/REPORT.md",
    "02_branche_systeme_solaire/couche_memoire_historique/STRESS_REPORT.md",
    "02_branche_systeme_solaire/couche_memoire_historique/VALIDATION.md",
    "02_branche_systeme_solaire/couche_memoire_historique/configs/primary.json",
    "02_branche_systeme_solaire/couche_memoire_historique/configs/smoke.json",
    "02_branche_systeme_solaire/couche_memoire_historique/data/PROVENANCE.md",
    "02_branche_systeme_solaire/couche_memoire_historique/data/processed/mpt_lr04_la2004.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/data/raw/INSOLN.LA2004.BTL.ASC",
    "02_branche_systeme_solaire/couche_memoire_historique/data/raw/La2004_README.TXT",
    "02_branche_systeme_solaire/couche_memoire_historique/data/raw/lisiecki2005-d18o-stack-noaa.txt",
    "02_branche_systeme_solaire/couche_memoire_historique/docs/PROTOCOL_MAPPING.md",
    "02_branche_systeme_solaire/couche_memoire_historique/docs/protocoles_sources/protocole_MPT_source.docx",
    "02_branche_systeme_solaire/couche_memoire_historique/docs/protocoles_sources/protocole_exoplanetaire_source.docx",
    "02_branche_systeme_solaire/couche_memoire_historique/pyproject.toml",
    "02_branche_systeme_solaire/couche_memoire_historique/requirements.txt",
    "02_branche_systeme_solaire/couche_memoire_historique/results/environment.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/controlled_forcings.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/ensemble_final_states.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/figures/controlled_forcings.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/figures/final_path_deltas.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/parameters.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/path_deltas.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/sample_trajectories_replicate_0.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/statistical_tests.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/exoplanet/summary.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/acceptance_tests.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/block_scores.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/data_quality.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/figures/mpt_power_ratio.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/figures/mpt_predictions.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/metrics.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/optimization.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/parameters.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/predictions.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results/mpt/summary.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results/run_summary.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/00_core_verification.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/a_mpt.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/b2_regime.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/b_exo.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/c_indep.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/corrected_run.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/corrected_run2.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/d_ladder.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_ensemble_stability.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_final_regime_report.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_final_regime_scan.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_materiality_map.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_multistability_final_states.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_relaxation.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_report.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/exoplanet/b_step_convergence.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/figures/stress_final_regime_scan.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/figures/stress_forcing_robustness.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/figures/stress_relaxation.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/figures/stress_spectral_capacity.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/figures/stress_split_sensitivity.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/figures/stress_surrogate_null.png",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/independence/c_forcing_robustness.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/independence/c_parameter_stability.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/independence/c_profile_likelihood.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/independence/c_report.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/independence/c_spectral_tradeoff.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/a_budget_metrics.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/a_predictions_wide.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/a_report.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/a_split_sensitivity.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/a_surrogate_null.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/d_budget_ladder.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/d_budget_ladder.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/e_hardened_verdict.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/mpt/e_hardened_verdict.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif/RAPPORT_PROSPECTIF.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif/attracteurs_par_mode.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/prospectif/preenregistrement.sha256",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/verdict.log",
    "02_branche_systeme_solaire/couche_memoire_historique/scripts/run_all.sh",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/__init__.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/__main__.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/cli.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/data.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/exoplanet.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/fastcore.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/metrics.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/mpt.py",
    "02_branche_systeme_solaire/couche_memoire_historique/src/oric_memory_tests/report.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/PREENREGISTREMENT_PROSPECTIF.md",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/a_mpt.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/b2_regime.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/b_exo.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/c_indep.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/core.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/d_budget_ladder.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/e_prospectif.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/figures.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/make_report.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/verdict.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/verify_core.py",
    "02_branche_systeme_solaire/couche_memoire_historique/tests/test_data.py",
    "02_branche_systeme_solaire/couche_memoire_historique/tests/test_exported_results.py",
    "02_branche_systeme_solaire/couche_memoire_historique/tests/test_fastcore.py",
    "02_branche_systeme_solaire/couche_memoire_historique/tests/test_metrics.py",
    "02_branche_systeme_solaire/couche_memoire_historique/tests/test_models.py",
    "02_branche_systeme_solaire/couche_memoire_historique/tests/test_stress_harness.py",
    "plan_directeur/campagne_plateforme/resultats/classification_soutiens.json",
    "plan_directeur/campagne_plateforme/scripts/classifier_soutiens.py",
    "plateforme/README.md",
    "plateforme/campagne_maximale_reelle/BILAN.md",
    "plateforme/campagne_maximale_reelle/BILAN_CORRIGE.md",
    "plateforme/campagne_maximale_reelle/PROVENANCE_EXOPLANET_ARCHIVE.json",
    "plateforme/campagne_maximale_reelle/PROVENANCE_GISTEMP.json",
    "plateforme/campagne_maximale_reelle/PROVENANCE_PAPASTAVROU_RNA.json",
    "plateforme/campagne_maximale_reelle/PROVENANCE_WINDELS_ANTIBIOTIC.json",
    "plateforme/campagne_maximale_reelle/TESTS_DONNEES_NASA.md",
    "plateforme/campagne_maximale_reelle/comparaison_nbody_la2004.json",
    "plateforme/campagne_maximale_reelle/data/antibiotic_cycles.csv",
    "plateforme/campagne_maximale_reelle/data/antibiotic_measurements.csv",
    "plateforme/campagne_maximale_reelle/data/ephemerides.csv",
    "plateforme/campagne_maximale_reelle/data/exoplanet_observations.csv",
    "plateforme/campagne_maximale_reelle/data/import_report.json",
    "plateforme/campagne_maximale_reelle/data/matter_transitions.csv",
    "plateforme/campagne_maximale_reelle/data/modern_climate_ensemble.csv",
    "plateforme/campagne_maximale_reelle/data/modern_climate_timeseries.csv",
    "plateforme/campagne_maximale_reelle/data/orbital_initial_conditions.csv",
    "plateforme/campagne_maximale_reelle/data/orbital_reference.csv",
    "plateforme/campagne_maximale_reelle/data/orbital_timeseries.csv",
    "plateforme/campagne_maximale_reelle/data/orbital_timeseries_nbody_dossier.csv",
    "plateforme/campagne_maximale_reelle/data/paleoclimate_timeseries.csv",
    "plateforme/campagne_maximale_reelle/data/prebiotic_rna_evolution.csv",
    "plateforme/campagne_maximale_reelle/data/provenance_reelle.json",
    "plateforme/campagne_maximale_reelle/data/relations.csv",
    "plateforme/campagne_maximale_reelle/degradation_phase_vs_spectre.json",
    "plateforme/campagne_maximale_reelle/memoire_distribuee_gistemp.json",
    "plateforme/campagne_maximale_reelle/memoire_distribuee_gistemp.py",
    "plateforme/campagne_maximale_reelle/preparer_donnees_reelles.py",
    "plateforme/campagne_maximale_reelle/resultats/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats/results.csv",
    "plateforme/campagne_maximale_reelle/resultats/results.json",
    "plateforme/campagne_maximale_reelle/resultats_avec_gistemp/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_avec_gistemp/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_avec_gistemp/results.json",
    "plateforme/campagne_maximale_reelle/resultats_corriges/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_corriges/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_corriges/results.json",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_exoplanetes_antibiotiques_reels/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_exoplanetes_antibiotiques_reels/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_exoplanetes_antibiotiques_reels/results.json",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_exoplanetes_reelles/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_exoplanetes_reelles/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_exoplanetes_reelles/results.json",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_multiregional/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_multiregional/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_multiregional/results.json",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_multiregional_corriges/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_multiregional_corriges/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_gistemp_multiregional_corriges/results.json",
    "plateforme/campagne_maximale_reelle/resultats_reels_etendus/REPORT.md",
    "plateforme/campagne_maximale_reelle/resultats_reels_etendus/results.csv",
    "plateforme/campagne_maximale_reelle/resultats_reels_etendus/results.json",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_Exoplanet_Archive/NASA_Exoplanet_Archive_PS_default.csv",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/GLB.Ts+dSST.csv",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries.zip",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleCombinedSeries_Band.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleCombinedSeries_Global.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleCombinedSeries_NH.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleCombinedSeries_SH.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleLSATSeries_Band.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleLSATSeries_Global.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleLSATSeries_NH.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleLSATSeries_SH.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleSSTSeries_Band.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleSSTSeries_Global.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleSSTSeries_NH.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/KeySeries/ensembleSSTSeries_SH.nc",
    "plateforme/campagne_maximale_reelle/sources_brutes/NASA_GISTEMP_v4/ZonAnn.Ts+dSST.csv",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/README.md",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/figure_data.zip",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/figure_data/figure_data/Papastavrou_23_fidelity_Table_S2_and_S3.xlsx",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/figure_data/figure_data/Papastavrou_23_fig_2_and_S2_data.xlsx",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/figure_data/figure_data/Papastavrou_23_fig_3_data.xlsx",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/figure_data/figure_data/Papastavrou_23_fig_4B_data.xlsx",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_10714366/figure_data/figure_data/Papastavrou_23_fig_S3_data.xlsx",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_7550302/evol_dynamics.csv",
    "plateforme/campagne_maximale_reelle/sources_brutes/Zenodo_7550302/phenotypes_after_evol.csv",
    "plateforme/campagne_maximale_reelle/vallee_des_rayons.json",
    "plateforme/campagne_maximale_reelle/vallee_des_rayons_exoplanetes.py",
    "plateforme/catalogue_tests.csv",
    "plateforme/commande_campagne_reelle.bat",
    "plateforme/commande_campagne_reelle.sh",
    "plateforme/commande_reproduction.bat",
    "plateforme/commande_reproduction.sh",
    "plateforme/criteria.csv",
    "plateforme/donnees/matter_transitions.csv",
    "plateforme/requirements.txt",
    "plateforme/source_corrigee/.github/workflows/ci.yml",
    "plateforme/source_corrigee/.gitignore",
    "plateforme/source_corrigee/CITATION.cff",
    "plateforme/source_corrigee/Dockerfile",
    "plateforme/source_corrigee/MANIFEST.sha256.json",
    "plateforme/source_corrigee/Makefile",
    "plateforme/source_corrigee/README.md",
    "plateforme/source_corrigee/VALIDATION_REPORT.md",
    "plateforme/source_corrigee/audit/moteurs_specialises.json",
    "plateforme/source_corrigee/audit/platform_audit.json",
    "plateforme/source_corrigee/audit/validation_results.json",
    "plateforme/source_corrigee/build/lib/oric_full/__init__.py",
    "plateforme/source_corrigee/build/lib/oric_full/__main__.py",
    "plateforme/source_corrigee/build/lib/oric_full/adapters/__init__.py",
    "plateforme/source_corrigee/build/lib/oric_full/adapters/existing_oric.py",
    "plateforme/source_corrigee/build/lib/oric_full/audit.py",
    "plateforme/source_corrigee/build/lib/oric_full/cli.py",
    "plateforme/source_corrigee/build/lib/oric_full/config.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/__init__.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/diagnostics.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/graph.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/intervention.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/memory.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/synthetic.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/viability.py",
    "plateforme/source_corrigee/build/lib/oric_full/core/xma.py",
    "plateforme/source_corrigee/build/lib/oric_full/criteria.py",
    "plateforme/source_corrigee/build/lib/oric_full/data_registry.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/__init__.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/antibiotics.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/astronomy.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/benchmark.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/biology.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/climate.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/matter.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/planetary.py",
    "plateforme/source_corrigee/build/lib/oric_full/domains/prebiotic.py",
    "plateforme/source_corrigee/build/lib/oric_full/engines.py",
    "plateforme/source_corrigee/build/lib/oric_full/environment.py",
    "plateforme/source_corrigee/build/lib/oric_full/models.py",
    "plateforme/source_corrigee/build/lib/oric_full/pipeline.py",
    "plateforme/source_corrigee/build/lib/oric_full/protocols.py",
    "plateforme/source_corrigee/build/lib/oric_full/provenance.py",
    "plateforme/source_corrigee/build/lib/oric_full/py.typed",
    "plateforme/source_corrigee/build/lib/oric_full/registry.py",
    "plateforme/source_corrigee/build/lib/oric_full/report.py",
    "plateforme/source_corrigee/build/lib/oric_full/resources/catalogue_tests.csv",
    "plateforme/source_corrigee/build/lib/oric_full/resources/catalogue_tests.json",
    "plateforme/source_corrigee/build/lib/oric_full/resources/plan_directeur.md",
    "plateforme/source_corrigee/build/lib/oric_full/resources/schemas_index.json",
    "plateforme/source_corrigee/build/lib/oric_full/runner.py",
    "plateforme/source_corrigee/build/lib/oric_full/stats.py",
    "plateforme/source_corrigee/build/lib/oric_full/synthetic_data.py",
    "plateforme/source_corrigee/catalogue/catalogue_tests.csv",
    "plateforme/source_corrigee/catalogue/catalogue_tests.json",
    "plateforme/source_corrigee/configs/campaign_full.yaml",
    "plateforme/source_corrigee/configs/campaign_priority1.yaml",
    "plateforme/source_corrigee/configs/campaign_smoke.yaml",
    "plateforme/source_corrigee/correctifs/appliquer_correctifs.py",
    "plateforme/source_corrigee/correctifs/correctifs.json",
    "plateforme/source_corrigee/criteria/criteria_template.csv",
    "plateforme/source_corrigee/dist/oric_full_research-0.2.1-py3-none-any.whl",
    "plateforme/source_corrigee/docs/ARCHITECTURE_TECHNIQUE.md",
    "plateforme/source_corrigee/docs/MATRICE_COUVERTURE.md",
    "plateforme/source_corrigee/docs/PLAN_DIRECTEUR_TESTS_ORI-C_COMPLET.md",
    "plateforme/source_corrigee/examples/data/antibiotic_cycles.csv",
    "plateforme/source_corrigee/examples/data/antibiotic_design.csv",
    "plateforme/source_corrigee/examples/data/antibiotic_lineages.csv",
    "plateforme/source_corrigee/examples/data/antibiotic_measurements.csv",
    "plateforme/source_corrigee/examples/data/benchmark_cases.csv",
    "plateforme/source_corrigee/examples/data/biology_cases.csv",
    "plateforme/source_corrigee/examples/data/body_properties.csv",
    "plateforme/source_corrigee/examples/data/cell_architecture.csv",
    "plateforme/source_corrigee/examples/data/chronometers.csv",
    "plateforme/source_corrigee/examples/data/endosymbiosis_events.csv",
    "plateforme/source_corrigee/examples/data/ephemerides.csv",
    "plateforme/source_corrigee/examples/data/isotope_tracers.csv",
    "plateforme/source_corrigee/examples/data/late_accretion_tracers.csv",
    "plateforme/source_corrigee/examples/data/matter_transitions.csv",
    "plateforme/source_corrigee/examples/data/modern_climate_ensemble.csv",
    "plateforme/source_corrigee/examples/data/modern_climate_timeseries.csv",
    "plateforme/source_corrigee/examples/data/molecular_inventory.csv",
    "plateforme/source_corrigee/examples/data/nucleosynthesis_yields.csv",
    "plateforme/source_corrigee/examples/data/orbital_initial_conditions.csv",
    "plateforme/source_corrigee/examples/data/orbital_reference.csv",
    "plateforme/source_corrigee/examples/data/orbital_timeseries.csv",
    "plateforme/source_corrigee/examples/data/paleoclimate_timeseries.csv",
    "plateforme/source_corrigee/examples/data/partition_experiments.csv",
    "plateforme/source_corrigee/examples/data/planetary_histories.csv",
    "plateforme/source_corrigee/examples/data/prebiotic_design.csv",
    "plateforme/source_corrigee/examples/data/prebiotic_lineages.csv",
    "plateforme/source_corrigee/examples/data/reaction_network.csv",
    "plateforme/source_corrigee/examples/data/relations.csv",
    "plateforme/source_corrigee/examples/data/states.csv",
    "plateforme/source_corrigee/examples/data/thermochemical_phases.csv",
    "plateforme/source_corrigee/examples/data/volatile_inventory.csv",
    "plateforme/source_corrigee/pkg/oric_full/__init__.py",
    "plateforme/source_corrigee/pkg/oric_full/__main__.py",
    "plateforme/source_corrigee/pkg/oric_full/adapters/__init__.py",
    "plateforme/source_corrigee/pkg/oric_full/adapters/existing_oric.py",
    "plateforme/source_corrigee/pkg/oric_full/audit.py",
    "plateforme/source_corrigee/pkg/oric_full/cli.py",
    "plateforme/source_corrigee/pkg/oric_full/config.py",
    "plateforme/source_corrigee/pkg/oric_full/core/__init__.py",
    "plateforme/source_corrigee/pkg/oric_full/core/diagnostics.py",
    "plateforme/source_corrigee/pkg/oric_full/core/graph.py",
    "plateforme/source_corrigee/pkg/oric_full/core/intervention.py",
    "plateforme/source_corrigee/pkg/oric_full/core/memory.py",
    "plateforme/source_corrigee/pkg/oric_full/core/synthetic.py",
    "plateforme/source_corrigee/pkg/oric_full/core/viability.py",
    "plateforme/source_corrigee/pkg/oric_full/core/xma.py",
    "plateforme/source_corrigee/pkg/oric_full/criteria.py",
    "plateforme/source_corrigee/pkg/oric_full/data_registry.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/__init__.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/antibiotics.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/astronomy.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/benchmark.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/biology.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/climate.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/matter.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/planetary.py",
    "plateforme/source_corrigee/pkg/oric_full/domains/prebiotic.py",
    "plateforme/source_corrigee/pkg/oric_full/engines.py",
    "plateforme/source_corrigee/pkg/oric_full/environment.py",
    "plateforme/source_corrigee/pkg/oric_full/models.py",
    "plateforme/source_corrigee/pkg/oric_full/pipeline.py",
    "plateforme/source_corrigee/pkg/oric_full/protocols.py",
    "plateforme/source_corrigee/pkg/oric_full/provenance.py",
    "plateforme/source_corrigee/pkg/oric_full/py.typed",
    "plateforme/source_corrigee/pkg/oric_full/registry.py",
    "plateforme/source_corrigee/pkg/oric_full/report.py",
    "plateforme/source_corrigee/pkg/oric_full/resources/catalogue_tests.csv",
    "plateforme/source_corrigee/pkg/oric_full/resources/catalogue_tests.json",
    "plateforme/source_corrigee/pkg/oric_full/resources/plan_directeur.md",
    "plateforme/source_corrigee/pkg/oric_full/resources/schemas_index.json",
    "plateforme/source_corrigee/pkg/oric_full/runner.py",
    "plateforme/source_corrigee/pkg/oric_full/stats.py",
    "plateforme/source_corrigee/pkg/oric_full/synthetic_data.py",
    "plateforme/source_corrigee/pkg/oric_full_research-0.2.1.dist-info/METADATA",
    "plateforme/source_corrigee/pkg/oric_full_research-0.2.1.dist-info/RECORD",
    "plateforme/source_corrigee/pkg/oric_full_research-0.2.1.dist-info/WHEEL",
    "plateforme/source_corrigee/pkg/oric_full_research-0.2.1.dist-info/entry_points.txt",
    "plateforme/source_corrigee/pkg/oric_full_research-0.2.1.dist-info/top_level.txt",
    "plateforme/source_corrigee/protocols_template/WP-A1.md",
    "plateforme/source_corrigee/protocols_template/WP-A2.md",
    "plateforme/source_corrigee/protocols_template/WP-A3.md",
    "plateforme/source_corrigee/protocols_template/WP-A4.md",
    "plateforme/source_corrigee/protocols_template/WP-A5.md",
    "plateforme/source_corrigee/protocols_template/WP-A6.md",
    "plateforme/source_corrigee/protocols_template/WP-B1.md",
    "plateforme/source_corrigee/protocols_template/WP-B2.md",
    "plateforme/source_corrigee/protocols_template/WP-B3.md",
    "plateforme/source_corrigee/protocols_template/WP-C1.md",
    "plateforme/source_corrigee/protocols_template/WP-C2.md",
    "plateforme/source_corrigee/protocols_template/WP-C3.md",
    "plateforme/source_corrigee/protocols_template/WP-C4.md",
    "plateforme/source_corrigee/protocols_template/WP-C5.md",
    "plateforme/source_corrigee/protocols_template/WP-C6.md",
    "plateforme/source_corrigee/protocols_template/WP-C7.md",
    "plateforme/source_corrigee/protocols_template/WP-CL1.md",
    "plateforme/source_corrigee/protocols_template/WP-CL2.md",
    "plateforme/source_corrigee/protocols_template/WP-CL3.md",
    "plateforme/source_corrigee/protocols_template/WP-CL4.md",
    "plateforme/source_corrigee/protocols_template/WP-M1.md",
    "plateforme/source_corrigee/protocols_template/WP-M2.md",
    "plateforme/source_corrigee/protocols_template/WP-M3.md",
    "plateforme/source_corrigee/protocols_template/WP-M4.md",
    "plateforme/source_corrigee/protocols_template/WP-M5.md",
    "plateforme/source_corrigee/protocols_template/WP-P1.md",
    "plateforme/source_corrigee/protocols_template/WP-P2.md",
    "plateforme/source_corrigee/protocols_template/WP-P3.md",
    "plateforme/source_corrigee/protocols_template/WP-P4.md",
    "plateforme/source_corrigee/protocols_template/WP-P5.md",
    "plateforme/source_corrigee/protocols_template/WP-P6.md",
    "plateforme/source_corrigee/protocols_template/WP-R1.md",
    "plateforme/source_corrigee/protocols_template/WP-R2.md",
    "plateforme/source_corrigee/protocols_template/WP-R3.md",
    "plateforme/source_corrigee/protocols_template/WP-R4.md",
    "plateforme/source_corrigee/protocols_template/WP-R5.md",
    "plateforme/source_corrigee/protocols_template/WP-R6.md",
    "plateforme/source_corrigee/protocols_template/WP-S1.md",
    "plateforme/source_corrigee/protocols_template/WP-S2.md",
    "plateforme/source_corrigee/protocols_template/WP-S3.md",
    "plateforme/source_corrigee/protocols_template/WP-T1.md",
    "plateforme/source_corrigee/protocols_template/WP-T2.md",
    "plateforme/source_corrigee/protocols_template/WP-T3.md",
    "plateforme/source_corrigee/protocols_template/WP-T4.md",
    "plateforme/source_corrigee/protocols_template/WP-T5.md",
    "plateforme/source_corrigee/protocols_template/WP-V1.md",
    "plateforme/source_corrigee/protocols_template/WP-V2.md",
    "plateforme/source_corrigee/protocols_template/WP-V3.md",
    "plateforme/source_corrigee/protocols_template/WP-V4.md",
    "plateforme/source_corrigee/protocols_template/WP-V5.md",
    "plateforme/source_corrigee/protocols_template/WP-V6.md",
    "plateforme/source_corrigee/pyproject.toml",
    "plateforme/source_corrigee/requirements.txt",
    "plateforme/source_corrigee/run_all.bat",
    "plateforme/source_corrigee/run_all.sh",
    "plateforme/source_corrigee/schemas/index.json",
    "plateforme/source_corrigee/schemas/schemas_index.json",
    "plateforme/source_corrigee/scripts/build_catalog.py",
    "plateforme/source_corrigee/scripts/import_exoplanet_archive_real.py",
    "plateforme/source_corrigee/scripts/import_gistemp_real.py",
    "plateforme/source_corrigee/scripts/import_papastavrou_rna_real.py",
    "plateforme/source_corrigee/scripts/import_windels_antibiotic_real.py",
    "plateforme/source_corrigee/scripts/run_everything.py",
    "plateforme/source_corrigee/scripts/specialiser_catalogue.py",
    "plateforme/source_corrigee/scripts/specialiser_catalogue_rna_reel.py",
    "plateforme/source_corrigee/src/oric_full/__init__.py",
    "plateforme/source_corrigee/src/oric_full/__main__.py",
    "plateforme/source_corrigee/src/oric_full/adapters/__init__.py",
    "plateforme/source_corrigee/src/oric_full/adapters/existing_oric.py",
    "plateforme/source_corrigee/src/oric_full/audit.py",
    "plateforme/source_corrigee/src/oric_full/cli.py",
    "plateforme/source_corrigee/src/oric_full/config.py",
    "plateforme/source_corrigee/src/oric_full/core/__init__.py",
    "plateforme/source_corrigee/src/oric_full/core/diagnostics.py",
    "plateforme/source_corrigee/src/oric_full/core/graph.py",
    "plateforme/source_corrigee/src/oric_full/core/intervention.py",
    "plateforme/source_corrigee/src/oric_full/core/memory.py",
    "plateforme/source_corrigee/src/oric_full/core/synthetic.py",
    "plateforme/source_corrigee/src/oric_full/core/viability.py",
    "plateforme/source_corrigee/src/oric_full/core/xma.py",
    "plateforme/source_corrigee/src/oric_full/criteria.py",
    "plateforme/source_corrigee/src/oric_full/data_registry.py",
    "plateforme/source_corrigee/src/oric_full/domains/__init__.py",
    "plateforme/source_corrigee/src/oric_full/domains/antibiotics.py",
    "plateforme/source_corrigee/src/oric_full/domains/astronomy.py",
    "plateforme/source_corrigee/src/oric_full/domains/benchmark.py",
    "plateforme/source_corrigee/src/oric_full/domains/biology.py",
    "plateforme/source_corrigee/src/oric_full/domains/climate.py",
    "plateforme/source_corrigee/src/oric_full/domains/matter.py",
    "plateforme/source_corrigee/src/oric_full/domains/planetary.py",
    "plateforme/source_corrigee/src/oric_full/domains/prebiotic.py",
    "plateforme/source_corrigee/src/oric_full/engines.py",
    "plateforme/source_corrigee/src/oric_full/environment.py",
    "plateforme/source_corrigee/src/oric_full/models.py",
    "plateforme/source_corrigee/src/oric_full/pipeline.py",
    "plateforme/source_corrigee/src/oric_full/protocols.py",
    "plateforme/source_corrigee/src/oric_full/provenance.py",
    "plateforme/source_corrigee/src/oric_full/py.typed",
    "plateforme/source_corrigee/src/oric_full/registry.py",
    "plateforme/source_corrigee/src/oric_full/report.py",
    "plateforme/source_corrigee/src/oric_full/resources/catalogue_tests.csv",
    "plateforme/source_corrigee/src/oric_full/resources/catalogue_tests.json",
    "plateforme/source_corrigee/src/oric_full/resources/plan_directeur.md",
    "plateforme/source_corrigee/src/oric_full/resources/schemas_index.json",
    "plateforme/source_corrigee/src/oric_full/runner.py",
    "plateforme/source_corrigee/src/oric_full/stats.py",
    "plateforme/source_corrigee/src/oric_full/synthetic_data.py",
    "plateforme/source_corrigee/src/oric_full_research.egg-info/PKG-INFO",
    "plateforme/source_corrigee/src/oric_full_research.egg-info/SOURCES.txt",
    "plateforme/source_corrigee/src/oric_full_research.egg-info/dependency_links.txt",
    "plateforme/source_corrigee/src/oric_full_research.egg-info/entry_points.txt",
    "plateforme/source_corrigee/src/oric_full_research.egg-info/requires.txt",
    "plateforme/source_corrigee/src/oric_full_research.egg-info/top_level.txt",
    "plateforme/source_corrigee/tests/test_catalogue.py",
    "plateforme/source_corrigee/tests/test_core.py",
    "plateforme/source_corrigee/tests/test_criteria.py",
    "plateforme/source_corrigee/tests/test_data_and_engines.py",
    "plateforme/source_corrigee/tests/test_pipeline.py",
    "plateforme/source_corrigee/tests/test_provenance.py",
    "plateforme/source_corrigee/tests/test_runner.py",
    "plateforme/wheel_corrige/oric_full_research-0.2.1-py3-none-any.whl",
    "plan_directeur/campagne_plateforme/README.md",
    "plan_directeur/campagne_plateforme/correctifs/appliquer_correctifs.py",
    "plan_directeur/campagne_plateforme/correctifs/correctifs.json",
    "plan_directeur/campagne_plateforme/donnees/ephemerides.csv",
    "plan_directeur/campagne_plateforme/donnees/matter_transitions.csv",
    "plan_directeur/campagne_plateforme/donnees/orbital_initial_conditions.csv",
    "plan_directeur/campagne_plateforme/donnees/orbital_reference.csv",
    "plan_directeur/campagne_plateforme/donnees/relations.csv",
    "plan_directeur/campagne_plateforme/donnees/states.csv",
    "plan_directeur/campagne_plateforme/platform_audit.json",
    "plan_directeur/campagne_plateforme/preenregistrement/catalogue_frozen.json",
    "plan_directeur/campagne_plateforme/preenregistrement/catalogue_frozen.json.sha256",
    "plan_directeur/campagne_plateforme/preenregistrement/criteria.csv",
    "plan_directeur/campagne_plateforme/preenregistrement/gel.json",
    "plan_directeur/campagne_plateforme/preenregistrement/gel_campagne2.json",
    "plan_directeur/campagne_plateforme/resultats/REPORT.md",
    "plan_directeur/campagne_plateforme/resultats/comptes_des_campagnes.json",
    "plan_directeur/campagne_plateforme/resultats/results.csv",
    "plan_directeur/campagne_plateforme/resultats/results.json",
    "plan_directeur/campagne_plateforme/scripts/geler_criteres.py",
    "plan_directeur/campagne_plateforme/scripts/mapper_donnees_reelles.py",
    "plan_directeur/campagne_plateforme/scripts/preregistrer_campagne2.py",
    "plan_directeur/audit_transversal.py",
    "plan_directeur/audit_transversal.json",
    "01_branche_matiere/base_transitions/construire_base.py",
    "01_branche_matiere/base_transitions/transitions_matiere.csv",
    "01_branche_matiere/base_transitions/completude.json",
    "00_socle/test_interventionnel/PORTEE_WP_S2.md",
    "00_socle/test_interventionnel/scripts/portee_wp_s2.py",
    "00_socle/test_interventionnel/resultats_portee/portee_wp_s2.json",
    "00_socle/test_interventionnel/resultats_portee/portee_wp_s2_execution_1.json",
    "00_socle/test_interventionnel/resultats_portee_wp_s2.log",
    "00_socle/carte_relationnelle/reconstruction_wp_m5.py",
    "00_socle/carte_relationnelle/resultats_analyse/reconstruction_wp_m5.json",
    "plan_directeur/PLAN_DIRECTEUR_TESTS.md",
    "plan_directeur/AVANCEMENT_DU_PLAN.md",
    "plan_directeur/construire_registre.py",
    "plan_directeur/REGISTRE_HYPOTHESES.csv",



    "00_socle/carte_relationnelle/analyse_graphe.py",
    "00_socle/carte_relationnelle/ANALYSE_GRAPHE.md",
    "00_socle/carte_relationnelle/resultats_analyse/analyse_graphe.json",
    "01_branche_matiere/README.md",
    "02_branche_systeme_solaire/README.md",
    "02_branche_systeme_solaire/article/ERRATUM.md",
    "02_branche_systeme_solaire/FILTRAGES_HISTORIQUES.md",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/f_tests_reels.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/g_tests_reels_2.py",
    "02_branche_systeme_solaire/couche_memoire_historique/stress/h_g2_corrige.py",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels_2.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/g2_corrige.log",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/f_tests_reels.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/g_tests_reels_2.json",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/t2_enregistrement_complet.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/t4_chronologie_spectrale.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/g1_validation_croisee.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/g3_convention_insolation.csv",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/RAPPORT_TESTS_REELS.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/RAPPORT_TESTS_REELS_2.md",
    "02_branche_systeme_solaire/couche_memoire_historique/results_stress/tests_reels/h_g2_corrige.json",
    "02_branche_systeme_solaire/application_climat/README.md",
    "03_branche_vivant/README.md",
    "03_branche_vivant/programme_prebiotique/PROGRAMME_PREBIOTIQUE.md",
    "03_branche_vivant/programme_prebiotique/valider_lignees.py",
    "03_branche_vivant/programme_prebiotique/schema_lignees/gabarit/lignees.csv",
    # Données enrichies dans le dossier : colonnes domaine_ferme, code_cible
    # et note_codage. Les paquets sources restent intacts.
    "00_socle/carte_relationnelle/data/noeuds_poc.csv",
    "00_socle/carte_relationnelle/data/relations_oric_47_provisoires.csv",
    # Suite de tests adaptée à l arborescence du dossier unique.
    # Script corrige dans le dossier, et ses sorties regenerees.
    "00_socle/test_interventionnel/scripts/analyse_exhaustive.py",
    "00_socle/test_interventionnel/resultats_exhaustifs/rapport_exhaustif.txt",
    "00_socle/test_interventionnel/resultats_exhaustifs/analyse_exhaustive.json",
    "00_socle/test_interventionnel/resultats_exhaustifs/analyse_exhaustive.pdf",
    "00_socle/test_interventionnel/resultats_exhaustifs/analyse_exhaustive.png",
    "00_socle/test_interventionnel/resultats_exhaustifs/CORRECTION_ANALYSE_EXHAUSTIVE.md",
    "00_socle/test_interventionnel/resultats_exhaustifs/Analyse_exhaustive_test_interventionnel_ORI-C_corrigee.pdf",
    "00_socle/tests/conftest.py",
    "00_socle/tests/test_carte_relationnelle.py",
    "00_socle/tests/test_documents.py",
    "00_socle/tests/test_integrite_dossier.py",
)

PLAN = [
    ("articles/ORI-C_Architecture_generale_du_programme.pdf",
     "ORI-C_Architecture_generale_du_programme.pdf",
     "Document principal, porte d entree du dossier"),
    ("dossier_consolide/02_carte_relationnelle", "00_socle/carte_relationnelle",
     "Carte des 40 transitions et 47 relations typées"),
    ("dossier_consolide/03_test_interventionnel", "00_socle/test_interventionnel",
     "Test interventionnel du chémostat"),
    ("dossier_consolide/tests", "00_socle/tests", "Suite de tests transversale"),
    ("dossier_consolide/05_schema_synthetique_stabilise",
     "00_socle/schema_synthetique", "Schéma synthétique stabilisé"),
    ("dossier_consolide/04_note_integration", "00_socle/note_integration",
     "Note d'intégration"),
    ("dossier_consolide/INVENTAIRE_PREUVES_CONSOLIDE.md",
     "00_socle/sources/INVENTAIRE_PREUVES_CONSOLIDE.md", "Inventaire des preuves"),
    ("dossier_consolide/RAPPORT_DURCISSEMENT_TESTS.md",
     "00_socle/sources/RAPPORT_DURCISSEMENT_TESTS.md", "Rapport de durcissement"),
    ("dossier_consolide/NOTE_DE_LECTURE.md",
     "00_socle/sources/NOTE_DE_LECTURE.md", "Note de lecture"),
    ("dossier_consolide/SEPARATION_DES_SCHEMAS.md",
     "00_socle/sources/SEPARATION_DES_SCHEMAS.md", "Séparation des schémas"),
    ("dossier_consolide/pytest.ini", "00_socle/pytest.ini", "Configuration pytest"),
    ("dossier_consolide/requirements.txt", "00_socle/requirements.txt", "Dépendances"),

    ("dossier_consolide/01_article", "01_branche_matiere/article",
     "Chronologie des architectures de la matière"),
    ("articles/ORI-C_document_unique_sans_fusion_des_contenus.pdf",
     "01_branche_matiere/article/variantes/"
     "ORI-C_document_unique_sans_fusion_des_contenus.pdf",
     "Variante sans fusion des contenus"),

    ("articles/Architecture_historique_du_Systeme_solaire_ORI-C_revue_approfondie (1).pdf",
     "02_branche_systeme_solaire/article/"
     "Architecture_historique_du_Systeme_solaire_ORI-C.pdf",
     "Article de la branche 2"),
    ("validation_ncorps", "02_branche_systeme_solaire/couche_astronomique",
     "Validation N-corps, 25 calculs"),
    ("tests_memoire", "02_branche_systeme_solaire/couche_memoire_historique",
     "Tests de mémoire historique, version corrigée"),

    ("articles/Le_climat_comme_architecture_historique.docx",
     "02_branche_systeme_solaire/application_climat/"
     "Le_climat_comme_architecture_historique_ORI-C.docx",
     "Application climatique, article separe hors chaine de preuve"),
    ("articles/Le_vivant_comme_terrain_ORI-C_mis_a_jour.docx",
     "03_branche_vivant/article/Le_vivant_comme_terrain_ORI-C.docx",
     "Article de la branche 3"),
]


def exclu(chemin: Path) -> bool:
    return (
        any(partie in EXCLUS_REPERTOIRES for partie in chemin.parts)
        or chemin.suffix in EXCLUS_SUFFIXES
        or chemin.name in EXCLUS_NOMS
    )


def copier(origine: Path, destination: Path) -> int:
    if origine.is_file():
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(origine, destination)
        return 1
    total = 0
    for chemin in sorted(origine.rglob("*")):
        if chemin.is_dir() or exclu(chemin):
            continue
        cible = destination / chemin.relative_to(origine)
        cible.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(chemin, cible)
        total += 1
    return total


def sources_manquantes(sources: Path) -> list[str]:
    return [relatif for relatif, _, _ in PLAN if not (sources / relatif).exists()]


def construire(sources: Path, destination: Path, verbeux: bool = True) -> int:
    manquants = sources_manquantes(sources)
    if manquants:
        raise SystemExit(
            "Sources manquantes, aucune modification effectuée :\n  "
            + "\n  ".join(manquants)
        )

    abri = None
    if destination.exists():
        abri = Path(tempfile.mkdtemp(prefix="oric_redige_"))
        for relatif in FICHIERS_REDIGES:
            origine = destination / relatif
            if origine.exists():
                cible = abri / relatif
                cible.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(origine, cible)
        shutil.rmtree(destination)
    destination.mkdir(parents=True)

    total = 0
    for relatif, cible, description in PLAN:
        nombre = copier(sources / relatif, destination / cible)
        total += nombre
        if verbeux:
            print(f"{nombre:>5}  {cible}  — {description}")

    if abri is not None:
        for relatif in FICHIERS_REDIGES:
            origine = abri / relatif
            if origine.exists():
                cible = destination / relatif
                cible.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(origine, cible)
                total += 1
        shutil.rmtree(abri, ignore_errors=True)
    return total


def ecrire_manifeste(destination: Path) -> int:
    lignes = []
    for chemin in sorted(destination.rglob("*")):
        if chemin.is_dir() or chemin.name == "MANIFEST.sha256" or exclu(chemin):
            continue
        digest = hashlib.sha256(chemin.read_bytes()).hexdigest()
        lignes.append(f"{digest}  {chemin.relative_to(destination).as_posix()}")
    (destination / "MANIFEST.sha256").write_text(
        "\n".join(lignes) + "\n", encoding="utf-8", newline="\n"
    )
    return len(lignes)


def _entrees(texte: str) -> dict[str, str]:
    resultat = {}
    for ligne in texte.splitlines():
        if not ligne.strip():
            continue
        empreinte, _, nom = ligne.partition("  ")
        resultat[nom] = empreinte
    return resultat


def verifier_reconstruction(sources: Path, destination: Path) -> int:
    with tempfile.TemporaryDirectory(prefix="oric_reconstruction_") as temporaire:
        essai = Path(temporaire) / "dossier"
        construire(sources, essai, verbeux=False)
        for relatif in FICHIERS_REDIGES:
            origine = destination / relatif
            if origine.exists():
                cible = essai / relatif
                cible.parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(origine, cible)
        ecrire_manifeste(essai)

        attendu = _entrees((destination / "MANIFEST.sha256").read_text(encoding="utf-8"))
        obtenu = _entrees((essai / "MANIFEST.sha256").read_text(encoding="utf-8"))

    ecarts = 0
    for nom in sorted(set(attendu) | set(obtenu)):
        a, b = attendu.get(nom), obtenu.get(nom)
        if a == b:
            continue
        etat = (
            "absent de la reconstruction" if b is None
            else "absent du dossier courant" if a is None
            else "empreinte différente"
        )
        print(f"  {etat:<30} {nom}")
        ecarts += 1

    if ecarts:
        print(f"\n{ecarts} écart(s). La reconstruction n'est pas identique.")
        return 1
    print(f"Reconstruction identique : {len(attendu)} entrées concordantes.")
    return 0


def main() -> int:
    racine = Path(__file__).resolve().parent
    parseur = argparse.ArgumentParser(
        description="Assemble ou vérifie le dossier unique ORI-C."
    )
    parseur.add_argument(
        "--sources", type=Path, default=racine.parent / "sources_ori_c",
        help="répertoire contenant les quatre arborescences sources",
    )
    parseur.add_argument("--destination", type=Path, default=racine)
    parseur.add_argument("--verifier-reconstruction", action="store_true")
    arguments = parseur.parse_args()

    sources = arguments.sources.resolve()
    destination = arguments.destination.resolve()

    if arguments.verifier_reconstruction:
        return verifier_reconstruction(sources, destination)

    total = construire(sources, destination)
    entrees = ecrire_manifeste(destination)
    print(f"\n{total} fichiers copiés, {entrees} entrées au manifeste.")
    print(f"Destination : {destination}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
